name: Salesforce CI

on:
    push:
        branches: master            
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2    

          - name: Set up Salesforce CLI
            uses: actions/setup-node@v2
            with:
              node-version: 18

          - name: Install Salesforce CLI
            run: npm install -g sfdx-cli

          - name: Authenticate to Salesforce
            run: |
               echo "Salesforce Authentication Running"
               sfdx:force: auth:password:generate --setalias  myCompanyOrg --username ankur@hope.com --password ${{ secrets.SALESFORCE_PASSWORD }}

          - name: Org Lists
            run: |     
                 echo "sfdx org list"

          - name: Run Apex Tests
            run: |
               echo "Running apex run test command"     
               sfdx apex run test -u myCompanyOrg -c -r human