name: Salesforce CI

on:
    push:
        branches: master
        paths:
          - force-app/**
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Initiating WorkFlow
            uses: actions/checkout@v2    

          - name: Set up Salesforce CLI
            uses: actions/setup-node@v2
            with:
              node-version: 18.15.0

          - name: Install Salesforce CLI
            run: npm install -g sfdx-cli
           
          - name: Checking Salesforce CLI
            run: sfdx --version         

          - name: Authenticate to Salesforce
            run: |
               echo "Salesforce Authentication Running"
               sfdx org login sfdx-url --set-default --${{secrets.SFDX_PROD_AUTH_URL}}

          - name: Org Lists
            run: |
                 echo "sfdx org list"
                 sfdx force: org :list     