name: Production Org Deployment

on:
  push:
    branches: master
    paths:
      - force-app/**
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Initiating WorkFlow
        uses: actions/checkout@v2

      - name: Setting up Salesforce CLI
        uses: actions/setup-node@v2
        with:
          node-version: 18.15.0

      - name: Installing Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Checking Salesforce CLI
        run: sfdx --version

      - name: Authorizing Salesforce Org
        run: |
          echo "Salesforce Authentication Running"               
          sfdx org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_PROD_AUTH_URL }}")

      - name: Running Apex Tests
        run: |
          sfdx apex run test -l RunLocalTests -w 15

      - name: Deploying Apex Class to Production Org
        run: |
          sfdx project deploy start
